### PR TITLE
Add resolvers to request

### PR DESCRIPTION
**Pull request by yashchenkoyurii**
Add resolvers to request
Change access modifiers like in Foundation TestCase
Rules can be arrays

### CODE REVIEW

**Comment by gluck1986** [comment]
yes!!! i need it!

**Comment by gluck1986** [comment]
Problem is more deeper, if you are interested - i forked this project and fix this problem, and fix several another. I can't wait, we use the plugin in our work.

**Comment by Asxer** [comment]
@gluck1986 Yes, of course, we are interested in it. Could you please make merge-request with it?

**Comment by gluck1986** [comment]
> @gluck1986 Yes, of course, we are interested in it. Could you please make merge-request with your fixes?

Hm, yes, but it take some time.

**Comment by gluck1986** [comment]
May i make a branch in your repo? In my repo i renamed namespaces and unbind several things.

**Comment by Asxer** [comment]
@gluck1986 As you wish

**Pull request closed without merging**
